### ISSUE TITLE
Create documentation for bridges (serial ports)

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/openc3.com#16]
See https://github.com/BallAerospace/COSMOS/issues/1508

**Comment by ryanmelt** [comment]
Serial ports can be implemented using COSMOS bridges, or directly if you are on linux running Docker on the host (not Docker Desktop).

Direct Serial Port Solution (Linux Docker only):

Add these lines (or equivalent) to the operator service in compose.yaml
```
   devices:
     - "/dev/ttyUSB0:/dev/ttyUSB0"
```

And In a shell:
sudo chmod 666 /dev/ttyUSB0

OR

Bridge Solution:

1. Requires a host Ruby installation (Ruby 3)
2. set host environment variable RUBYLIB=<Path to cosmos/openc3/lib folder>
3. set host environment variable RUBYGEMS_URL=https://rubygems.org
4. cd cosmos/openc3 && bundle install && rake build && cd ../..
5. ruby cosmos/openc3/bin/openc3cli bridgesetup
6. Edit the generated bridge configuration file (change serial port settings)
7. ruby cosmos/openc3/bin/openc3cli bridge
8. Change your plugin to connect to be a tcpip_client_interface instead of serial_interface and point host to host.docker.internal (or 172.17.0.1) and appropriate port
9. Install updated plugin to server

**Comment by ryanmelt** [comment]
https://openc3.com/docs/v5/bridges
